### ISSUE TITLE
Reported Resources$NotFoundException

### ISSUE THREAD

**Issue by RayBa82** [RayBa82/DVBViewerController#47]
{main} android.content.res.Resources$NotFoundException: String resource ID #0x0 at android.content.res.Resources.getText(Resources.java:312) at android.widget.TextView.setText(TextView.java:4417) at org.dvbviewer.controller.ui.fragments.ChannelEpg.onActivityCreated(ChannelEpg.java:143) at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1970) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092) at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248) at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738) at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613) at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570) at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163) at android.support.v4.view.ViewPager.populate(ViewPager.java:1106) at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552) at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514) at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:946) at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2910) at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37) at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276) at org.dvbviewer.controller.ui.fragments.EpgPager.onLoadFinished(EpgPager.java:334) at org.dvbviewer.controller.ui.fragments.EpgPager.onLoadFinished(EpgPager.java:54) at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476) at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444) at android.support.v4.content.Loader.deliverResult(Loader.java:126) at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105) at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37) at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249) at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77) at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466) at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48) at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by RayBa82** [comment]
good chance that 083bd446e70c62da15cb8cf7fae4d3e8101cc9d1 could fix this crash :-)
