### ISSUE TITLE
NPE at EPGDetails

### ISSUE THREAD

**Issue by RayBa82** [RayBa82/DVBViewerController#54]
{main} java.lang.RuntimeException: Unable to start activity ComponentInfo{org.dvbviewer.controller/org.dvbviewer.controller.ui.phone.IEpgDetailsActivity}: java.lang.NullPointerException at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) at android.app.ActivityThread.access$600(ActivityThread.java:141) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:137) at android.app.ActivityThread.main(ActivityThread.java:5041) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.NullPointerException at org.dvbviewer.controller.ui.fragments.EPGDetails.onCreateView(SourceFile:75) at android.support.v4.app.Fragment.performCreateView(SourceFile:1962) at android.support.v4.app.an.a(SourceFile:1067) at android.support.v4.app.an.a(SourceFile:1248) at android.support.v4.app.q.run(SourceFile:738) at android.support.v4.app.an.e(SourceFile:1613) at android.support.v4.app.aj.p(SourceFile:330) at android.support.v4.app.ae.onStart(SourceFile:547) at org.dvbviewer.controller.ui.base.BaseActivity.onStart(SourceFile:66) at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1164) at android.app.Activity.performStart(Activity.java:5114) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) ... 11 more

**Comment by RayBa82** [comment]
should be fixed with 9d2f124000f819044cade0873a28f143b12cb832
