### ISSUE TITLE
Failed to parse the xml data

### ISSUE THREAD

**Issue by smoralis** [RayBa82/DVBViewerController#70]
When trying to retrieve the channel list the app fails to parse the xml data.
Using RS 1.33.2.0
Branch material-icons

04-04 21:56:07.924 18533-20434/org.dvbviewer.controller D/DVBViewerServerRequest: http://192.168.1.160:8089/api/getchannelsxml.html?logo=1
04-04 21:56:08.100 18533-20434/org.dvbviewer.controller E/ChannelPager: Error loading ListData
                                                                        org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 150876: not well-formed (invalid token)
                                                                            at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:515)
                                                                            at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
                                                                            at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
                                                                            at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
                                                                            at android.util.Xml.parse(Xml.java)
                                                                            at org.dvbviewer.controller.io.data.ChannelHandler.parse(ChannelHandler.java:55)
                                                                            at org.dvbviewer.controller.ui.fragments.ChannelPager.performRefresh(ChannelPager.java:498)
                                                                            at org.dvbviewer.controller.ui.fragments.ChannelPager.access$400(ChannelPager.java:78)
                                                                            at org.dvbviewer.controller.ui.fragments.ChannelPager$1.loadInBackground(ChannelPager.java:392)
                                                                            at org.dvbviewer.controller.ui.fragments.ChannelPager$1.loadInBackground(ChannelPager.java:387)
                                                                            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
                                                                            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
                                                                            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
                                                                            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by smoralis** [comment]
To answer myself this thread helped me fix it.
http://www.dvbviewer.tv/forum/topic/59240-failed-to-parse-the-xml-data-error/
